---
###############################################################################
#
# tasks/docker-repo.yml
#
# Task for splunk-sc4s
#
###############################################################################

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    validate_certs: no
  tags: docker-repo

# Uncomment if desired
#- name: Enable Docker Edge repo
#  ini_file:
#    dest: /etc/yum.repos.d/docer-ce.repo
#    section: 'docker-ce-edge'
#    option: enabled
#    value: 0

#- name: Enable Docker Test repo
#  ini_file:
#    dest: /etc/yum.repos.d/docer-ce.repo
#    section: 'docker-ce-test'
#    option: enabled
#    value: 0
